cat <<EOF
Net-RPC port: @@NETRPCPORT@@
XML-RPC port: @@XMLRPCPORT@@
Testfield PGPORT: @@PGPORT@@
Testfield: http://@@USERERP@@.testfield.@@RB_SERVER_URL@@
URL: http://@@USERERP@@.@@RB_SERVER_URL@@

EOF

if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

