#!/bin/bash

NETRPC_PORT=@@NETRPCPORT@@
WEB_PORT=@@WEBPORT@@
XMLRPC_PORT=@@XMLRPCPORT@@
XMLRPCS_PORT=@@XMLRPCPORT@@

UNIFIELDADMIN=admin
UNIFIELDPASSWORD=admin

DBPASSWORD=toto
DBADDR=127.0.0.1
DBUSERNAME=toto
DBPORT=@@PGPORT@@
DBPREFIX=''

SERVER_HOST=127.0.0.1
SERVER_TMPDIR=/home/@@USERERP@@
SERVER_ENVNAME=lightweight

DBPATH=/usr/lib/postgresql/8.4/bin/
FORCED_DATE=2016-05-25
KEY_FETCH_BENCH=@@CLOUD_BENCH_KEY@@

OWNCLOUDUSERNAME=
OWNCLOUDPASSWORD=
