#!/bin/sh

### BEGIN INIT INFO
# Provides:		openerp-server
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Should-Start:		$network
# Should-Stop:		$network
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Enterprise Resource Management software
# Description:		Open ERP is a complete ERP and CRM software.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/home/@@USERERP@@/unifield-server/bin/openerp-server.py
NAME=openerp-server-@@USERERP@@
DESC=openerp-server-@@USERERP@@

USER=@@USERERP@@

LOG=/home/@@USERERP@@/log/openerp-server.log
CONFIG=/home/@@USERERP@@/etc/openerprc
PIDFILE=/home/@@USERERP@@/etc/openerp-server.pid
test -x ${DAEMON} || exit 0

set -e
. /lib/lsb/init-functions
case "${1}" in
	start)
		status="0"
		pidofproc -p $PIDFILE $DAEMON >/dev/null || status="$?"
		if [ "$status" = 0 ]; then
			echo "Service is already running"
			exit 1
		fi
		echo -n "Starting ${DESC}: "
		touch ${PIDFILE}
		start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
			--chuid ${USER} --background --make-pidfile \
			--exec ${DAEMON} -- --config=${CONFIG} \
			    --logfile=${LOG}
		chown $USER $PIDFILE
		echo "${NAME}."
		;;

	stop)
		echo -n "Stopping ${DESC}: "

		start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
			--oknodo --retry TERM/10/KILL/5

		echo "${NAME}."
		;;

	restart|force-reload)
		echo -n "Restarting ${DESC}: "

		start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
			--oknodo --retry TERM/10/KILL/5

		sleep 1

		start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
			--chuid ${USER} --background --make-pidfile \
			--exec ${DAEMON} -- --config=${CONFIG} \
			    --logfile=${LOG}

		chown $USER $PIDFILE
		echo "${NAME}."
		;;

	*)
		N=/etc/init.d/${NAME}
		echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
