truncate account_move_line CASCADE;
truncate account_move CASCADE;
truncate account_analytic_line CASCADE;
truncate account_bank_statement_line CASCADE;
truncate account_bank_statement CASCADE;
truncate sale_order_line CASCADE;
truncate sale_order CASCADE;
truncate purchase_order_line CASCADE;
truncate purchase_order CASCADE;
truncate shipment CASCADE;
truncate stock_move CASCADE;
truncate stock_picking CASCADE;
truncate ir_attachment CASCADE;

truncate tender CASCADE;
truncate tender_line CASCADE;
truncate account_invoice_line CASCADE;
truncate account_invoice CASCADE;
truncate account_commitment_line CASCADE;
truncate account_commitment CASCADE;
truncate hr_payroll_msf CASCADE;
truncate funding_pool_distribution_line CASCADE;
truncate analytic_distribution CASCADE;
truncate cost_center_distribution_line CASCADE;
truncate account_move_reconcile CASCADE;
truncate hq_entries CASCADE;
truncate msf_budget_line CASCADE;
truncate account_move_unreconcile CASCADE;
truncate account_cashbox_line CASCADE;
truncate account_subscription CASCADE;
truncate account_model CASCADE;
truncate automated_export CASCADE;
truncate automated_import CASCADE;
truncate cash_request CASCADE;
truncate claim_event CASCADE;
truncate financing_contract_contract CASCADE;
truncate financing_contract_donor CASCADE;
truncate free_1_distribution_line CASCADE;
truncate free_2_distribution_line CASCADE;
truncate initial_stock_inventory CASCADE;
truncate manage_expired_stock CASCADE;
truncate msf_accrual_line CASCADE;
truncate monthly_review_consumption CASCADE;
truncate physical_inventory CASCADE;
truncate product_history_consumption CASCADE;
truncate product_mass_update CASCADE;
truncate real_average_consumption CASCADE;
truncate replenishment_inventory_review CASCADE;
truncate replenishment_location_config CASCADE;
truncate replenishment_order_calc CASCADE;
truncate replenishment_segment CASCADE;
truncate replenishment_segment_line CASCADE;
truncate export_report_stock_inventory;
truncate stock_mission_report_line CASCADE;
truncate stock_mission_report_line_location;
truncate return_claim CASCADE;
truncate msf_budget CASCADE;
truncate weekly_forecast_report CASCADE;
truncate sync_client_update_received;
truncate sync_client_update_to_send;
truncate sync_client_message_received;
truncate sync_client_message_to_send;
truncate deleted_object;
update sync_client_version set patch=NULL;
delete from hr_employee;
delete from res_log;
delete from audittrail_log_sequence where model='account.move';
create index audittrail_log_sequence_sequence on audittrail_log_sequence(sequence);
ALTER TABLE ir_sequence DISABLE TRIGGER ALL;
delete from ir_sequence where code in ('account.move', 'at_account.move');
ALTER TABLE ir_sequence ENABLE TRIGGER ALL;
delete from audittrail_log_line where object_id in (select m.id from  ir_model m where m.model in ('account.analytic.line', 'account.move.line', 'account.move', 'account.bank.statement.line', 'account.bank.statement', 'sale.order.line', 'sale.order', 'purchase.order.line', 'purchase.order', 'shipment', 'stock.move', 'stock.picking', 'ir.attachment', 'hr.employee', 'tender', 'tender.line', 'account.invoice.line', 'account.invoice', 'account.commitment.line', 'account.commitment', 'hr.payroll.msf', 'funding.pool.distribution.line', 'analytic.distribution', 'cost.center.distribution.line', 'account.move.reconcile', 'hq.entries', 'msf.budget.line', 'account.move.unreconcile', 'account.cashbox.line', 'account.subscription', 'account.model', 'automated.export', 'automated.import', 'cash.request', 'claim', 'claim.event', 'account.bank.statement.line', 'cost.center.distribution.line', 'financing.contract.contract',  'supplier.catalogue.line', 'account.mcdb',  'account.move',  'account.cashbox.line',  'account.move.unreconcile',  'funding.pool.distribution.line', 'financing.contract.donor',  'hq.entries', 'account.move.line', 'account.analytic.line', 'stock.mission.report.line', 'stock.mission.report.line.location', 'free.1.distribution.line', 'free.2.distribution.line', 'msf.budget'));
delete from ir_model_data where model in ('account.analytic.line', 'account.move.line', 'account.move', 'account.bank.statement.line', 'account.bank.statement', 'sale.order.line', 'sale.order', 'purchase.order.line', 'purchase.order', 'shipment', 'stock.move', 'stock.picking', 'ir.attachment', 'hr.employee', 'tender', 'tender.line', 'account.invoice.line', 'account.invoice', 'account.commitment.line', 'account.commitment', 'hr.payroll.msf', 'funding.pool.distribution.line', 'analytic.distribution', 'cost.center.distribution.line', 'account.move.reconcile', 'hq.entries', 'msf.budget.line', 'account.move.unreconcile', 'account.cashbox.line', 'account.subscription', 'account.model', 'automated.export', 'automated.import', 'cash.request', 'claim', 'claim.event', 'account.bank.statement.line', 'cost.center.distribution.line', 'financing.contract.contract',  'supplier.catalogue.line', 'account.mcdb',  'account.move',  'account.cashbox.line',  'account.move.unreconcile',  'funding.pool.distribution.line', 'financing.contract.donor',  'hq.entries', 'account.move.line', 'account.analytic.line', 'stock.mission.report.line', 'stock.mission.report.line.location', 'free.1.distribution.line', 'free.2.distribution.line', 'sync.monitor', 'msf.budget');
analyze;
